### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by bowen-xu**
Seperate `nace.py` into several files for maintainability.

### CODE REVIEW

**Comment by patham9** [comment]
Unfortunately I had already started modularizing, just not yet commited. But let's see how we can combine it as you have some potential improvements in there which I don't have!
Does the Numpy dependence and custom deepcopy make it faster? If so, how much?

**Comment by bowen-xu** [comment]
> Does the Numpy dependence and custom deepcopy make it faster? If so, how much?

Currently no. It makes the program 15% slower. But it would be more convenient to use numpy if you consider to optimize the code. For example, in localObserve function, we can use subscripts to access an area of the array, and it would be much faster than using loops. Of course it's not necessary to use numpy.

**Comment by bowen-xu** [comment]
@patham9 I'll close this pr and wait for your update on the modularized code.

**Comment by patham9** [comment]
I have added it, I also used part of your PR like the separate prettyprint.py I didn't have before.

**Pull request closed without merging**
